/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'IcoMoonBasic\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-report-3' : '&#x21;',
			'icon-report-2' : '&#x22;',
			'icon-report-1' : '&#x23;',
			'icon-info-1' : '&#x24;',
			'icon-info-3' : '&#x25;',
			'icon-info-2' : '&#x26;',
			'icon-help-circle' : '&#x27;',
			'icon-box-add' : '&#x28;',
			'icon-disc-1' : '&#x29;',
			'icon-zoom-1' : '&#x2a;',
			'icon-attachment' : '&#x2b;',
			'icon-video-3' : '&#x2c;',
			'icon-video-1' : '&#x2d;',
			'icon-users-1' : '&#x2e;',
			'icon-user-add' : '&#x2f;',
			'icon-user-1' : '&#x30;',
			'icon-edit-1' : '&#x31;',
			'icon-trophy-1' : '&#x32;',
			'icon-tickets' : '&#x33;',
			'icon-talk-bubble-5' : '&#x34;',
			'icon-talk-bubble-4' : '&#x35;',
			'icon-talk-bubble-2' : '&#x36;',
			'icon-chat-2' : '&#x37;',
			'icon-chat-1' : '&#x38;',
			'icon-talk-bubble-1' : '&#x39;',
			'icon-star-filled' : '&#x3a;',
			'icon-star-outline' : '&#x3b;',
			'icon-shopping-cart-1' : '&#x3c;',
			'icon-shirt' : '&#x3d;',
			'icon-settings-gear-3' : '&#x3e;',
			'icon-settings-gear-2' : '&#x3f;',
			'icon-search-2' : '&#x40;',
			'icon-search-1' : '&#x41;',
			'icon-home' : '&#x42;',
			'icon-quotations-2' : '&#x43;',
			'icon-quotations-1' : '&#x44;',
			'icon-print-2' : '&#x45;',
			'icon-print-1' : '&#x46;',
			'icon-plus-square' : '&#x47;',
			'icon-plus-rounded' : '&#x48;',
			'icon-plus-circle' : '&#x49;',
			'icon-document' : '&#x4a;',
			'icon-song' : '&#x4b;',
			'icon-music-1' : '&#x4c;',
			'icon-minus-square' : '&#x4d;',
			'icon-minus-rounded' : '&#x4e;',
			'icon-minus-circle' : '&#x4f;',
			'icon-minimize-2' : '&#x50;',
			'icon-minimize-1' : '&#x51;',
			'icon-maximize-2' : '&#x52;',
			'icon-maximize-1' : '&#x53;',
			'icon-map-pin-2' : '&#x54;',
			'icon-map-pin-1' : '&#x55;',
			'icon-map-5' : '&#x56;',
			'icon-map-4' : '&#x57;',
			'icon-map-3' : '&#x58;',
			'icon-map-2' : '&#x59;',
			'icon-map-1' : '&#x5a;',
			'icon-logout-2' : '&#x5b;',
			'icon-logout-1' : '&#x5c;',
			'icon-locked-2' : '&#x5d;',
			'icon-locked-1' : '&#x5e;',
			'icon-list-4' : '&#x5f;',
			'icon-list-3' : '&#x60;',
			'icon-list-2' : '&#x61;',
			'icon-list-1' : '&#x62;',
			'icon-info-card-2' : '&#x63;',
			'icon-images' : '&#x64;',
			'icon-image-2' : '&#x65;',
			'icon-image-1' : '&#x66;',
			'icon-key' : '&#x67;',
			'icon-key-1' : '&#x68;',
			'icon-heart-open-1' : '&#x69;',
			'icon-heart-closed-1' : '&#x6a;',
			'icon-flag-1' : '&#x6b;',
			'icon-email-square' : '&#x6c;',
			'icon-email-rounded' : '&#x6d;',
			'icon-email-circle' : '&#x6e;',
			'icon-email-2' : '&#x6f;',
			'icon-email-1' : '&#x70;',
			'icon-upload-1' : '&#x71;',
			'icon-download-2' : '&#x72;',
			'icon-download-1' : '&#x73;',
			'icon-play-1' : '&#x74;',
			'icon-phone-1' : '&#x75;',
			'icon-dashboard-open' : '&#x76;',
			'icon-dashboard-filled' : '&#x77;',
			'icon-controls-stop' : '&#x78;',
			'icon-controls-prev' : '&#x79;',
			'icon-controls-play' : '&#x7a;',
			'icon-controls-pause' : '&#x7b;',
			'icon-controls-next' : '&#x7c;',
			'icon-close' : '&#x7d;',
			'icon-close-circle' : '&#x7e;',
			'icon-checkmark' : '&#xe000;',
			'icon-checkmark-square' : '&#xe001;',
			'icon-checkmark-rounded' : '&#xe002;',
			'icon-checkmark-circle' : '&#xe003;',
			'icon-tag-2' : '&#xe004;',
			'icon-tag-1' : '&#xe005;',
			'icon-camera-2' : '&#xe006;',
			'icon-camera-1' : '&#xe007;',
			'icon-arrow-small-up-1' : '&#xe008;',
			'icon-arrow-small-right-1' : '&#xe009;',
			'icon-arrow-small-left-1' : '&#xe00a;',
			'icon-arrow-small-down-1' : '&#xe00b;',
			'icon-arrow-circle-up-1' : '&#xe00c;',
			'icon-arrow-circle-right-1' : '&#xe00d;',
			'icon-arrow-circle-left-1' : '&#xe00e;',
			'icon-arrow-circle-down-1' : '&#xe00f;',
			'icon-arrow-2-right' : '&#xe010;',
			'icon-arrow-2-left' : '&#xe011;',
			'icon-arrow-1-up' : '&#xe012;',
			'icon-arrow-1-right' : '&#xe013;',
			'icon-arrow-1-left' : '&#xe014;',
			'icon-arrow-1-down' : '&#xe015;',
			'icon-wave-square' : '&#xe016;',
			'icon-wave-rounded' : '&#xe017;',
			'icon-wave-circle' : '&#xe018;',
			'icon-wave' : '&#xe019;',
			'icon-calendar-4' : '&#xe01a;',
			'icon-calendar-2' : '&#xe01b;',
			'icon-calendar-1' : '&#xe01c;',
			'icon-calendar-3' : '&#xe01d;',
			'icon-ideaden-light-bg' : '&#xe01e;',
			'icon-ideaden-dark-bg' : '&#xe01f;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c) {
			addIcon(el, icons[c[0]]);
		}
	}
};